
---
format:
  html: {toc: true, toc-depth: 3, theme: cosmo, number-sections: false, output-file: index.html}
fontsize: 0.9em
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}
toc-title-numbers: false
number-depth: 0

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="index_files/md-default0.js" type="text/javascript"></script><script src="index_files/md-default1.js" type="text/javascript"></script>


### Jaryt Salvo
**Date:** **9/13/24**

**Fall 2024 | CS7300 Unsupervised Learning**

*************

This project contains solutions to Homework 1 from the Unsupervised Learning course (CS7300) using Clojure. The primary purpose is to answer the given questions and demonstrate understanding of the concepts. While Clojure is used throughout the notebook, it's important to note that the implementation serves as a learning tool to better understand the processes in action. Leveraging high performance libraries like [`Neanderthal`](https://neanderthal.uncomplicate.org/) and [`Tablecloth`](https://github.com/scicloj/tablecloth) to showcase the implementation of key concepts.

Code in this notebook demonstrates certain applications of various linear algebra techniques, such as matrix multiplication, normalization, and standardization. Not all methods mentioned are implemented in code (e.g. Lasso, Ridge regression, or PCA). The Clojure implementations provided focus on demonstrating key concepts I could quickly enough hack together and serve as practical examples where feasible.

The code is organized into different sections corresponding to each homework problem, with detailed explanations of the algorithms and mathematical concepts involved. We utilize Clojure and its associated libraries, such as `scicloj.clay` for rendering, `tablecloth` for data manipulation, and `fastmath` for mathematical operations.

#### Utils

The `utils.clj` file contains various utility functions and helpers used throughout the homework solutions. It includes:

- Formatting functions for markdown and LaTeX rendering
- Data preprocessing and normalization functions
- Helper functions for implementing unsupervised learning algorithms

These utilities are designed to streamline the implementation process and provide reusable components for data analysis and visualization in the context of unsupervised learning.

The code in the `src/assignments` folder was rendered with [Clay](https://scicloj.github.io/clay/) and deployed with [Github Pages](https://pages.github.com/).


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: src/index.clj</small></small></pre></div>
```
